language: node_js
node_js:
  - "0.12"
  - "iojs"
addons:
  code_climate:
    repo_token:
      secure: "2005bf1ec399571b1699ec34e7e835d6c44dfdda2cf4c60128b486e22fad8dd9"
after_script:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate
